version: 2.1

executors:
  dandelion-executor:
    docker:
        - image: amsharifian/dandelion:micro
        user: "dandelion"

    working_directory: ~/repos

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  build-prep:
    executor: dandelion--executor

    steps:

    # Perform a "default" checkout to get ssh set up.
      - checkout:
          path: dandelion

      - run:
          command: |
            date > date.prep
            printenv
            ls -l

workflows:

  build_and_test:
    jobs:
      - build-prep
